version: '3.4'

services:
  db:
    image: mysql:9.1.0
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3308:3306"
    expose:
      - 3306
    networks:
      - erudio-network
  rest-with-spring-boot:
    image: flavio73/rest-with-spring-boot
    build: .
    working_dir: /rest-with-spring-boot-and-java-erudio
    restart: always
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: ${SPRING_DATASOURCE_URL}
      SPRING.DATASOURCE.USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING.DATASOURCE.PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    command: mvn spring-boot:run
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - erudio-network
  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - erudio-network

volumes:
  portainer_data:

networks:
  erudio-network:
    driver: bridge