name: Continuous Integration and Delivery with Github actions

on:
  push:
    branches:
      - "main"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Setup Java 21
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: maven

    - name: Build Application JAR
      working-directory: ./rest-with-spring-boot-and-java-erudio
      run: mvn clean package

    - name: Docker Composer Build
      working-directory: ./rest-with-spring-boot-and-java-erudio
      run: docker compose build

    - name: Push to Docker Container Registry
      run: | 
        docker tag ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot:latest ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot:${{ github.run_id }}

        docker push ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot:${{ github.run_id }}

